name: Gatekeeper

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Gatekeeping:
    name: Gatekeeping
    runs-on: ubuntu-18.04
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set .NET Core version
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "5.0.x"

    - name: Nuget cache
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore packages
      run: dotnet restore

    - name: Pack
      run: dotnet pack Orbital.Core.csproj --no-restore -c Release

